on:
  push
jobs:
    push-alpine:
        runs-on: ubuntu-latest
        name: Push alpine image
        steps:
            - name: Checkout master
              uses: actions/checkout@master
            - name: Print Branch name
              run: echo running on branch ${GITHUB_REF##*/}
            - name: Build and publish image
              uses: ilteoood/docker_buildx@master
              with:
                publish: true
                tag: ${GITHUB_REF##*/}-alpine
                imageName: traccar/traccar
                dockerHubUser: ${{ secrets.DOCKER_USER }}
                dockerHubPassword: ${{ secrets.DOCKER_PASS }}
                dockerFile: alpine/Dockerfile
    push-debian:
        runs-on: ubuntu-latest
        name: Push debian image
        steps:
            - name: Checkout master
              uses: actions/checkout@master
            - name: Print Branch name
              run: echo running on branch ${GITHUB_REF##*/}
            - name: Build and publish image
              uses: ilteoood/docker_buildx@master
              with:
                publish: true
                tag: ${GITHUB_REF##*/}-debian
                platform: linux/amd64
                imageName: traccar/traccar
                dockerHubUser: ${{ secrets.DOCKER_USER }}
                dockerHubPassword: ${{ secrets.DOCKER_PASS }}
                dockerFile: debian/Dockerfile
