on:
  push:
    branches:
      - main
    paths:
      - '**/Dockerfile'

jobs:
    build:
        runs-on: ubuntu-latest
        name: Build image job
        steps:
            - name: Checkout master
              uses: actions/checkout@master
            - name: Build and publish image
              uses: ilteoood/docker_buildx@master
              with:
                publish: true
                imageName: arribada/traccar
                dockerHubUser: ${{ secrets.DOCKER_USER }}
                dockerHubPassword: ${{ secrets.DOCKER_PASS }}
                dockerFile: alpine/Dockerfile